### ISSUE TITLE
Addin not available for Website Project

### ISSUE THREAD

**Issue by andrew-lewis-apl** [rfennell/ParametersXmlAddin#12]
When editing a website project instead of a web application project,  no context menu appears for the web.config file.

**Comment by rfennell** [comment]
I will to get a repo when I get a chance

**Comment by rfennell** [comment]
OK a bit confused over types of project

Can you confirm the exact template type in use that does not work. Can you give me repo steps to create the failing project type

Looking at the code I can't see an obvious reason for it to work

**Comment by andrew-lewis-apl** [comment]
I checked the version installed and it is 1.7.

I select File New Project and choose asp.net web site

I right click on web.config and no menu appears.

If I do file new web application the menu is there.

I am using visual studio 2017 latest.

**Comment by rfennell** [comment]
Old school....

I can repo the problem, I guess it must be the lack of the project file causing the issue. I thought the logic just used the file name, maybe it can't get without the project file providing an inventory  

Not sure of we call that a bug or enhancement, but I will look into it

**Comment by andrew-lewis-apl** [comment]
Yes the lack of a project file causes issues with the build as well.

I have had to go to a .publishproj and a .pubxml file based build. 

At least the problem is not just my machine

**Comment by rfennell** [comment]
The basic issue is the **BeforeQueryStatusOk** event is not being call. I found this issue reported on [stackoverflow](https://stackoverflow.com/questions/27687954/visual-studio-extensibility-provideautoload-for-package-cs-for-every-ui-context) which sounds the same issue. The recommended fix was to add

```
[ProvideAutoLoad(VSConstants.UICONTEXT.NoSolution_string)]
[ProvideAutoLoad(VSConstants.UICONTEXT.SolutionExists_string)]
[ProvideAutoLoad(VSConstants.UICONTEXT.SolutionHasMultipleProjects_string)]
[ProvideAutoLoad(VSConstants.UICONTEXT.SolutionHasSingleProject_string)]
```

Problem is this did not work, I will keep looking, but not holding out too much of hope at this point.

**Comment by rfennell** [comment]
Have looked more and seems there is no solution, so closing the issue
