### ISSUE TITLE
Synchronous load

### ISSUE THREAD

**Issue by JohannBlais** [rfennell/ParametersXmlAddin#15]
Hello,

The extension generates a warning when installed on VS 2019.
It seems to be using a synchronous load, which is now deprecated.

![image](https://user-images.githubusercontent.com/1086147/55625689-c7854400-57a9-11e9-90c6-260ad21e29e9.png)

Cheers !

**Comment by rfennell** [comment]
OK that needs fixing, from  my tests it works for now, but I need to sort that out.

Thanks for reporting it

**Comment by rfennell** [comment]
After some investigation the notes to fix the problem are [here](https://github.com/Microsoft/VSSDK-Extensibility-Samples/tree/master/AsyncPackageMigration). 

However, I cannot find the required API calls. I notew the same in [this similar report](https://github.com/tunnelvisionlabs/FindInSolutionExplorer/issues/17), the comment there is it is a bug VS2019.

I will monitor that thread
