### ISSUE TITLE
xml element case sensitive

### ISSUE THREAD

**Issue by phoenix-chen-2016** [rfennell/ParametersXmlAddin#18]
generate parameters.xml content
        <parameter name="AuthToken" description="" defaultvalue="__AuthToken__" tags="">
		<parameterentry kind="XmlFile" scope="\\App.config$" match="/configuration/appSettings/add[@key='AuthToken']/@value" />
	</parameter>

command line execute 
msdeploy -verb:sync -source:contentPath=.... -dest:package=xxx.zip -declareParamFile="parameters.xml"

response
Error: 需要元素 'parameterEntry'。
parameters.xml
Error count: 1.

if change parameters.xml content
        <parameter name="AuthToken" description="" defaultValue="__AuthToken__" tags="">
		<parameterEntry kind="XmlFile" scope="\\App.config$" match="/configuration/appSettings/add[@key='AuthToken']/@value" />
	</parameter>

execute correct

**Comment by rfennell** [comment]
Sorry you will have to give me more context. Can you provide 

- a copy of the web.config it is generating off.
- the bad parameters.xml
- the fixed version you are using of parameters.xml

**Comment by phoenix-chen-2016** [comment]
my app.config
[https://raw.githubusercontent.com/phoenix-chen-2016/ParameterScenario/master/App.config](https://raw.githubusercontent.com/phoenix-chen-2016/ParameterScenario/master/App.config)

bad parameters.xml
[https://raw.githubusercontent.com/phoenix-chen-2016/ParameterScenario/master/parameters.xml](https://raw.githubusercontent.com/phoenix-chen-2016/ParameterScenario/master/parameters.xml)

fixed parameters.xml
https://raw.githubusercontent.com/phoenix-chen-2016/ParameterScenario/master/fixed-parameters.xml

Scenario repos
[https://github.com/phoenix-chen-2016/ParameterScenario](https://github.com/phoenix-chen-2016/ParameterScenario)

after build, execute pack.ps1 fail
execute pack-fixed.ps1 correct

**Comment by rfennell** [comment]
@phoenix-chen-2016  Thanks for the excellent repo of the problem. 

Seems the issue is the casing, strange that has never shown up before.  I will look at creating a patch

Thanks for reporting the issue

**Comment by rfennell** [comment]
Fixed the problem with version 1.10
