### ISSUE TITLE
This extension is not installable on any currently installed products.

### ISSUE THREAD

**Issue by joaquimcid** [rfennell/ParametersXmlAddin#3]
When I try to install the plugin the installation does not correctly install.

The log result:

04/12/2015 11:05:10 - Searching for applicable products...
04/12/2015 11:05:11 - Found installed product - Microsoft Visual Studio Premium 2013
04/12/2015 11:05:11 - Found installed product - Microsoft Visual Studio Professional 2013
04/12/2015 11:05:11 - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
04/12/2015 11:05:11 - Found installed product - Global Location
04/12/2015 11:05:11 - Found installed product - ssms
04/12/2015 11:05:11 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by rfennell** [comment]
I will have a look at the issue, I assume a manifest issue in the version checking as the code is common for all versions of the IDE

**Comment by rfennell** [comment]
V1.3 should fix this, it is pushed to the VS Gallery as well as being a release here.
