### ISSUE TITLE
Nice to have: make the casing for defaultvalue configurable

### ISSUE THREAD

**Issue by frankvaneykelen** [rfennell/ParametersXmlAddin#4]
Thanks for your great extension! 

Here's a small change that would make it even better for me: make the casing for the "defaultvalue" attribute value configurable.

Now it's always an uppercase version of the "name" attribute value: defaultvalue="__CDNURI__".
An alternative casing option I would like to have is leaving the case unchanged: defaultvalue="__CdnUri__"

**Comment by rfennell** [comment]
I need to see the best way to add custom option flags

**Comment by rfennell** [comment]
This has been released in version 1.4
You can find the settings on Tools > Options > Parameters XML Addin

**Comment by frankvaneykelen** [comment]
Thank you very much! That was fast...
