### ISSUE TITLE
Nice to have: make adding a description attribute optional

### ISSUE THREAD

**Issue by frankvaneykelen** [rfennell/ParametersXmlAddin#5]
The generator now always adds a not so useful description attribute: description="Description for cdnUri".

I would like to have the option to generate a Parameters.xml file without the description attributes

**Comment by rfennell** [comment]
I need to see the best way to add custom option flags

**Comment by frankvaneykelen** [comment]
Great! One more thing: I just realized that the description attribute might be required.  In that case making it optional will result in an invalid parameters file....

**Comment by rfennell** [comment]
I think I can get away with making the description empty, at least that is what I intend to try

**Comment by rfennell** [comment]
This has been released in version 1.4
You can find the settings on Tools > Options > Parameters XML Addin
